import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    image: {
        width: 250,
        height: 120,
        borderRadius: 4,
        marginBottom: 5,
    },
    text: {
        flexDirection: 'row',
        justifyContent: 'center',
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
        paddingHorizontal: 5,
        paddingVertical: 5,
    },
    container: {
        flex: 1,
    },
    buttonsContainer: {
        flex: 1,
        justifyContent: 'space-around',
        flexDirection: 'row',
        borderRadius: 15,
        marginVertical: 10,
        marginHorizontal: 10,
    },
    listContainer: {
        flex: 8,
        borderRadius: 15,
        marginVertical: 10,
    },
    listHeader: {
        fontSize: 20,
        fontWeight: 'bold',
        marginLeft: 5,
    },
    listText: {
        fontSize: 15,
        fontWeight: 'bold',
        flex: 8,
        alignSelf: 'center',
    },
    scanning: {
        alignSelf: 'center',
        marginHorizontal: 20,
        marginVertical: 150,
        height: 200,
        width: 200,
        fontSize: 30,
    },
    toggleBluetooth: {
        borderRadius: 15,
        borderWidth: 3,
        borderColor: '#ccd1d1',
        backgroundColor: '#8F46B3',
        paddingHorizontal: 15,
        paddingVertical: 10,
        marginTop: 20,
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    button: {
        borderRadius: 15,
        borderWidth: 3,
        borderColor: '#ccd1d1',
        backgroundColor: '#8F46B3',
        paddingHorizontal: 15,
        paddingVertical: 10,
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    pairContainer: {
        marginHorizontal: 5,
        flexDirection: 'row',
        alignSelf: 'flex-end',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 20,
        borderTopWidth: 1,
        borderColor: 'grey',
        paddingHorizontal: 15,
    },
});
