import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    wrapper: {
        position: 'absolute',
        marginVertical: 30,
        alignSelf: 'center',
        height: 600,
    },
    windowContainer: {
        flex: 4,
        borderRadius: 15,
        borderColor: '#ccd1d1',
        backgroundColor: '#8F46B3',
    },
    cameraContainer: {
        width: 320,
        flex: 2,
        flexDirection: 'row',
        borderRadius: 15,
    },
    fixedRatio: {
        flex: 1,
        borderRadius: 15,
    },
    container: {
        flex: 1,
        flexDirection: 'column',
        backgroundColor: 'black',
    },
    preview: {
        flex: 1,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    button: {
        flex: 1,
        alignSelf: 'flex-end',
        marginRight: 8,
        borderRadius: 15,
        borderWidth: 3,
        borderColor: '#ccd1d1',
        paddingHorizontal: 5,
        paddingVertical: 5,
        position: 'absolute',

    },
    bottomButton: {
        flex: 1,
        alignSelf: 'flex-end',
        fontSize: 20,
        color: 'black',
        backgroundColor: '#8F46B3',
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 15,
        borderWidth: 3,
        borderColor: 'white',
        marginVertical: 15,
        position: 'absolute',
    },
    exitCamera: {
        alignSelf: 'flex-end',
        position: 'absolute',
        fontSize: 20,
        color: 'black',
        backgroundColor: 'white',
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 15,
        borderWidth: 3,
        borderColor: '#8F46B3',
    },
    bottomText: {
        flexDirection: 'row',
        justifyContent: 'center',
        fontSize: 15,
        fontWeight: 'bold',
        color: 'white',
    },
    text: {
        flexDirection: 'row',
        justifyContent: 'center',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#8F46B3',
    },
    reverseCamera: {
        alignSelf: 'flex-start',
        position: 'absolute',
        fontSize: 20,
        color: 'black',
        backgroundColor: 'white',
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 15,
        borderWidth: 3,
        borderColor: '#8F46B3',
    },
    bottomButtonsContainer: {
        height: 55,
        borderRadius: 15,
        flexDirection: 'column',
    },
});
